.global __CINT
__CINT   = 0XFF81
.global __IOINIT
__IOINIT = 0XFF84
.global __RAMTAS
__RAMTAS = 0XFF87
.global __RESTOR
__RESTOR = 0XFF8A
.global __VECTOR
__VECTOR = 0XFF8D
.global __SETMSG
__SETMSG = 0xFF90
.global __SECOND
__SECOND = 0XFF93
.global __TKSA
__TKSA   = 0XFF96
.global __MEMTOP
__MEMTOP = 0XFF99
.global __MEMBOT
__MEMBOT = 0XFF9C
.global __SCNKEY
__SCNKEY = 0XFF9F
.global __SETTMO
__SETTMO = 0XFFA2
.global __ACPTR
__ACPTR  = 0XFFA5
.global __CIOUT
__CIOUT  = 0XFFA8
.global __UNTLK
__UNTLK  = 0XFFAB
.global __UNLSN
__UNLSN  = 0XFFAE
.global __LISTEN
__LISTEN = 0XFFB1
.global __TALK
__TALK   = 0XFFB4
.global __READST
__READST = 0XFFB7
.global __SETLFS
__SETLFS = 0XFFBA
.global __SETNAM
__SETNAM = 0XFFBD
.global __OPEN
__OPEN   = 0XFFC0
.global __CLOSE
__CLOSE  = 0XFFC3
.global __CHKIN
__CHKIN  = 0XFFC6
.global __CHKOUT
__CHKOUT = 0XFFC9
.global __CLRCHN
__CLRCHN = 0XFFCC
.global __CHRIN
__CHRIN  = 0XFFCF
.global __CHROUT
__CHROUT = 0XFFD2
.global __LOAD
__LOAD   = 0XFFD5
.global __SAVE
__SAVE   = 0XFFD8
.global __SETTIM
__SETTIM = 0XFFDB
.global __RDTIM
__RDTIM  = 0XFFDE
.global __STOP
__STOP   = 0XFFE1
.global __GETIN
__GETIN  = 0XFFE4
.global __CLALL
__CLALL  = 0XFFE7
.global __UDTIM
__UDTIM  = 0XFFEA
.global __SCREEN
__SCREEN = 0XFFED
.global __PLOT
__PLOT   = 0XFFF0
.global __IOBASE
__IOBASE = 0XFFF3
