name: Package
on:
  push:
    branches: [ main ]
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Install Ubuntu build dependencies.
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get -y install ninja-build
      - name: Install Windows build dependencies.
        if: startsWith(matrix.os, 'windows')
        run: choco install curl ninja zip microsoft-build-tools
      - name: Install MacOS tools
        if: startsWith(matrix.os, 'macos')
        run: brew update && brew install ninja

      - name: Fetch the latest Ubuntu llvm-mos release.
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos/releases/download/llvm-mos-linux-main/llvm-mos-linux-main.tar.xz
          tar -xvf llvm-mos-linux-main.tar.xz
      - name: Fetch the latest Windows llvm-mos release.
        if: startsWith(matrix.os, 'windows')
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos/releases/download/llvm-mos-linux-main/llvm-mos-windows-main.zip
          unzip llvm-mos-windows-main.zip
      - name: Fetch the latest Mac llvm-mos release.
        if: startsWith(matrix.os, 'macos')
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos/releases/download/llvm-mos-linux-main/llvm-mos-darwin-main.tar.xz
          tar -xvf llvm-mos-darwin-main.tar.xz

      - name: Check out the SDK.
        uses: actions/checkout@v2

      - name: Build the SDK.
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/llvm-mos -G "Ninja" ..
          ninja install

      - name: Archive the Linux SDK.
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          tar -cJvf llvm-mos-linux.tar.xz llvm-mos
      - name: Archive the Windows SDK.
        if: startsWith(matrix.os, 'windows')
        run: |
          zip -FSr -9 -v llvm-mos-windows.zip llvm-mos
      - name: Archive the Mac SDK.
        if: startsWith(matrix.os, 'macos')
        run: |
          tar -cJvf llvm-mos-macos.tar.xz llvm-mos

      - name: Dispatch Test Suite
        if: startsWith(matrix.os, 'ubuntu')
        uses: llvm-mos/repository-dispatch@v1
        with:
          token: ${{ secrets.TEST_SUITE_ACCESS_TOKEN }}
          repository: llvm-mos/llvm-test-suite
          event-type: on-sdk-update
          client-payload: '{"head_commit": ${{ toJSON(github.event.head_commit) }}}'
