name: Package
on:
  push:
    branches: [ main ]
jobs:
  package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Install Ubuntu build dependencies.
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get -y install ninja-build
      - name: Install Windows build dependencies.
        if: startsWith(matrix.os, 'windows')
        run: choco install curl ninja zip
      - name: Install MacOS tools
        if: startsWith(matrix.os, 'macos')
        run: brew update && brew install ninja

      - name: Check out the SDK.
        uses: actions/checkout@v2

      - name: Fetch the latest Ubuntu llvm-mos release.
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos/releases/download/llvm-mos-linux-main/llvm-mos-linux-main.tar.xz
          tar -xvf llvm-mos-linux-main.tar.xz
      - name: Fetch the latest Windows llvm-mos release.
        if: startsWith(matrix.os, 'windows')
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos/releases/download/llvm-mos-windows-main/llvm-mos-windows-main.zip
          unzip llvm-mos-windows-main.zip
      - name: Fetch the latest Mac llvm-mos release.
        if: startsWith(matrix.os, 'macos')
        run: |
          curl -LO https://github.com/llvm-mos/llvm-mos/releases/download/llvm-mos-darwin-main/llvm-mos-darwin-main.tar.xz
          tar -xvf llvm-mos-darwin-main.tar.xz

      - name: Build the SDK.
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/llvm-mos -G "Ninja" ..
          ninja install

      - name: Archive the POSIX SDKs.
        if: ${{!startsWith(matrix.os, 'windows')}}
        run: tar -cJvf llvm-mos.tar.xz llvm-mos
      - name: Archive the Windows SDK.
        if: startsWith(matrix.os, 'windows')
        run: zip -FSr -9 -v llvm-mos.zip llvm-mos

      - name: Upload the Linux SDK.
        if: startsWith(matrix.os, 'ubuntu')
        uses: softprops/action-gh-release@v1
        with:
          name: Prerelease Linux SDK
          tag_name: linux-prerelease
          files: llvm-mos.tar.xz
          prerelease: true
          generate_release_notes: true
      - name: Upload the Windows SDK.
        if: startsWith(matrix.os, 'windows')
        uses: softprops/action-gh-release@v1
        with:
          name: Prerelease Windows SDK
          tag_name: windows-prerelease
          files: llvm-mos.zip
          prerelease: true
          generate_release_notes: true
      - name: Upload the Mac SDK.
        if: startsWith(matrix.os, 'macos')
        uses: softprops/action-gh-release@v1
        with:
          name: Prerelease Mac OS SDK
          tag_name: macos-prerelease
          files: llvm-mos.tar.xz
          prerelease: true
          generate_release_notes: true

      - name: Dispatch Test Suite
        if: startsWith(matrix.os, 'ubuntu')
        uses: llvm-mos/repository-dispatch@v1
        with:
          token: ${{ secrets.TEST_SUITE_ACCESS_TOKEN }}
          repository: llvm-mos/llvm-test-suite
          event-type: on-sdk-update
          client-payload: '{"head_commit": ${{ toJSON(github.event.head_commit) }}}'
